name: Scheduled Fetch and Build
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 6 * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Fetch latest data
      run: |-
        curl "https://www.mi5.gov.uk/UKThreatLevel/UKThreatLevel.xml" > latest.xml
        
    - name: Commit and push if it changed
      run: |-
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git diff --quiet || (git add -A && git commit -m "Updated with latest")
        git push
        
  build:
    needs: fetch
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Configure pip caching  
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install Python dependencies
      run: python -m pip install -r requirements.txt
      
    - name: Check for new articles
      run: python 'python/content.py'
      
    - name: Commit and push changes
      run: |-
        git diff
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git diff --quiet || (git add -A && git commit -m "Updated with latest")
        git push
